version: "3.7"

services:
  selenoid:
    image: aerokube/selenoid:latest
    network_mode: bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/etc/selenoid
    command: [
      "-conf", "/etc/selenoid/browsers.json",
      "-limit", "5",
      "-timeout", "5m"
    ]
    ports:
      - "4444:4444"

  selenoid-ui:
    image: aerokube/selenoid-ui:latest
    network_mode: bridge
    ports:
      - "8081:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
