version: "3.8"

services:
  selenoid:
    image: aerokube/selenoid:latest
    ports:
      - "4444:4444"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/etc/selenoid
    command:
      - "-conf"
      - "/etc/selenoid/browsers.json"
      - "-limit"
      - "5"
      - "-timeout"
      - "5m"

  selenoid-ui:
    image: aerokube/selenoid-ui:latest
    ports:
      - "8081:8080"
    command:
      - "--selenoid-uri"
      - "http://selenoid:4444"
    depends_on:
      - selenoid
